# =============================================
# ASSEMBLE CONFIG
# =============================================

dest:            _gh_pages
assets:          assets
ext:             .html


# =============================================
# Data
# =============================================

# Metadata
data:
- {name: 'site', src: ['.assemblerc.yml']} # This is magic :-) it adds data in this file to the `site` object
- data/*.json


# =============================================
# Templates
# =============================================

# Includes
partials:          templates/includes/**/*.hbs

# Layouts
layout:            post                  # the default layout to use
layoutdir:         templates/layouts     # directory with layouts
layoutext:         .hbs                  # the extension used by layouts


# =============================================
# EXTENSIONS
# =============================================

# middleware:  ["extensions/middleware/*.js"]


# =============================================
# BLOG SETTINGS
# =============================================

blog:
  flatten:         false
  cwd:             content/posts
  posts:           '**/*.md'

  # Dest directory and structure
  dest:            blog/
  structure:       ":basename/index.html"

# =============================================
# URL
# =============================================

url:
  homepage:  http://assemble.io