# =============================================
# DEST CONFIG
# =============================================

base:         _gh_pages
dest:         _gh_pages
ext:          .html

# Dest assets
public:       <%= site.dest %>/public

# =============================================
# Data
# =============================================

# Metadata
data:
# - {name: 'site', src: ['.assemblerc.yml']} # This is magic :-) it adds data in this file to the `site` object
# - {name: 'pkg',  src: ['package.json']}
- data/*.json

date:         <%= new Date() %>

description:  <%= pkg.description %>


# =============================================
# Templates
# =============================================

# Assets > fonts, icons, images etc.
assets:       <%= site.dest %>/public
images:       <%= site.assets %>/images
fonts:        <%= site.assets %>/fonts

# Styles
styles:       styles

# Scripts
scripts:      scripts

# Content
# content:      content


# =============================================
# TEMPLATES
# =============================================

templates:    templates

# partials
# components:   templates/components
includes:     templates/includes
snippets:     templates/snippets

# layouts
layouts:      templates/layouts
layoutext:    .hbs
layout:       post


# =============================================
# EXTENSIONS
# =============================================

helpers: "extensions/helpers"
middleware: "extensions/middleware"


# =============================================
# BLOG SETTINGS
# =============================================

blog:
  flatten:    false
  cwd:        content/posts
  posts:      '**/*.md'

  # Dest directory and structure
  dest:       "<%= site.dest %>/blog"
  structure:  ":basename/index.html"

# =============================================
# URL
# =============================================

url:
  homepage:   http://assemble.io
