layout: "post"
layoutext: ".hbs"
layoutdir: "templates/layouts/"
assets: "assets"
ext: ".html"
partials:
  - "templates/includes/**/*.hbs"
blog:
  posts:
    - "**/*.md"
  dest: "blog/"
  cwd: "templates/posts/"
  expand: true
  flatten: false
  structure: ":basename/index.html"
  archives:
    name: "archive"
    plural: "archives"
    related_pages:
      template: "templates/layouts/list.hbs"
      dest: "<%= blog.dest %>archives/"
      pagination:
        prop: "num"
        limit: 2
        sortby: "date"
      permalinks:
        structure: ":archive/:numindex.html"
